#!/bin/env bash
#USAGE flag "-p --profile <profile>" help="Build with the specified profile" default="dev" {
#USAGE   choices "dev" "release"
#USAGE }
#USAGE flag "-t --target <target>" help="The target to build" default="x86_64-unknown-linux-musl" {
#USAGE   choices "aarch64-apple-darwin" "aarch64-linux-android" "aarch64-unknown-linux-musl" "x86_64-unknown-linux-musl"
#USAGE }

set -e

# Set build mode variable
BUILD_MODE="debug"
if [[ "${usage_profile?}" == "release" ]]; then
    BUILD_MODE="release"
fi

echo
echo "TARGET : ${usage_target?}"
echo "PROFILE: ${usage_profile?}"
echo

cargo build --profile "${usage_profile?}" --target "${usage_target?}"

echo "Building testing container image..."
docker build -t dotsy-dev .

echo "Running testing container..."
docker run --hostname="laptop" -it --rm \
    -v "$(pwd)/target/${usage_target}/${BUILD_MODE}/dotsy:/usr/local/bin/dotsy:Z" \
    -v "$(pwd)/example:/home/testuser/dotfiles:Z" \
    dotsy-dev
