#!/bin/env bash
#USAGE flag "-p --profile <profile>" help="Build with the specified profile" default="dev" {
#USAGE   choices "dev" "release"
#USAGE }
#USAGE flag "-t --target <target>" help="The target to build" default="x86_64-unknown-linux-musl" {
#USAGE   choices "aarch64-apple-darwin" "aarch64-linux-android" "aarch64-unknown-linux-musl" "x86_64-unknown-linux-musl"
#USAGE }

set -e

# Set build mode variable
BUILD_MODE="debug"
if [[ "${usage_profile?}" == "release" ]]; then
    BUILD_MODE="release"
fi

echo
echo "TARGET : ${usage_target?}"
echo "PROFILE: ${usage_profile?}"
echo

cargo build --profile "${usage_profile?}" --target "${usage_target?}"

echo "Building testing container image..."
docker build \
    --build-arg USER_ID="$(id -u)" \
    --build-arg GROUP_ID="$(id -g)" \
    -t dotbee-dev .

TEMP_DOTFILES=$(mktemp -d)
cp -r example/. "$TEMP_DOTFILES"
chmod -R u+w "$TEMP_DOTFILES"

# Ensure cleanup on exit
trap 'rm -rf "$TEMP_DOTFILES"' EXIT

# Detect if we are using podman
PODMAN_FLAGS=""
if docker --version | grep -qi podman; then
    PODMAN_FLAGS="--userns=keep-id"
fi

echo "Running testing container..."
docker run --hostname="laptop" -it --rm \
    $PODMAN_FLAGS \
    -v "$(pwd)/target/${usage_target}/${BUILD_MODE}/dotbee:/usr/local/bin/dotbee:Z" \
    -v "$TEMP_DOTFILES:/home/testuser/dotfiles:Z" \
    dotbee-dev
