#:schema https://gitlab.com/rogue87/dotsy/-/raw/main/schema/dotsy.json

[settings]
auto_detect_profile = true
on_conflict = "ask" # Options: "abort", "adopt", "overwrite", "skip", "ask". Default: "ask"
icon_style = "nerdfont"

[global.links]
"~/.config/fastfetch" = "profiles/global/fastfetch"
"~/.config/fish" = "profiles/global/fish"
"~/.config/git" = "profiles/global/git"
"~/.config/nvim" = "profiles/global/nvim"

[profiles.laptop.links]
"~/.config/kitty" = "profiles/laptop/kitty"

[profiles.termux.links]
"~/.termux" = "profiles/termux/termux-settings"
"~/.config/tmux" = "profiles/termux/tmux"
