stages:
  - build
  - release

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  BINARY_NAME: dotsy

.build_template:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG

build-linux:
  extends: .build_template
  image: rust:1.92.0
  parallel:
    matrix:
      - TARGET: x86_64-unknown-linux-gnu
        PLATFORM: linux-x64
      - TARGET: aarch64-unknown-linux-gnu
        PLATFORM: linux-arm64
      - TARGET: x86_64-unknown-linux-musl
        PLATFORM: linux-x64-musl
  cache:
    key: "${PLATFORM}"
    paths:
      - .cargo/bin/
      - .cargo/registry/index/
      - .cargo/registry/cache/
      - .cargo/git/db/
      - target/
  before_script:
    - apt-get update && apt-get install -y xz-utils zip
    - if [ "$PLATFORM" = "linux-arm64" ]; then apt-get install -y gcc-aarch64-linux-gnu; fi
    - if [ "$PLATFORM" = "linux-x64-musl" ]; then apt-get install -y musl-tools; fi
    - rustup target add $TARGET
  script:
    - |
      if [ "$PLATFORM" = "linux-arm64" ]; then
        export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
      fi
      cargo build --release --target $TARGET
      PKG_NAME="${BINARY_NAME}-${CI_COMMIT_TAG}-${PLATFORM}"
      BIN_FILE="target/$TARGET/release/${BINARY_NAME}"

      tar -czf ${PKG_NAME}.tar.gz -C "$(dirname "${BIN_FILE}")" "${BINARY_NAME}"
      tar -cJf ${PKG_NAME}.tar.xz -C "$(dirname "${BIN_FILE}")" "${BINARY_NAME}"
      zip -j "${PKG_NAME}.zip" "${BIN_FILE}"

      cp "${BIN_FILE}" "${PKG_NAME}"
  artifacts:
    paths:
      - ${BINARY_NAME}-${CI_COMMIT_TAG}-${PLATFORM}*


upload:
  stage: release
  image: curlimages/curl:latest
  needs:
    - job: build-linux
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      for FILE in ${BINARY_NAME}-${CI_COMMIT_TAG}-*; do
        echo "Uploading $FILE..."
        curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
             --upload-file "$FILE" \
             "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${BINARY_NAME}/${CI_COMMIT_TAG}/${FILE}"
      done

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: upload
      artifacts: false
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      ASSETS_FLAGS=""
      for PLATFORM in linux-x64 linux-arm64 linux-x64-musl; do
        PREFIX="${BINARY_NAME}-${CI_COMMIT_TAG}-${PLATFORM}"
        for EXT in "" ".tar.gz" ".tar.xz" ".zip"; do
          FILENAME="${PREFIX}${EXT}"
          URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${BINARY_NAME}/${CI_COMMIT_TAG}/${FILENAME}"
          ASSETS_FLAGS="${ASSETS_FLAGS} --assets-link {\"name\":\"${FILENAME}\",\"url\":\"${URL}\"}"
        done
      done
      
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --description "Release of version $CI_COMMIT_TAG" \
        $ASSETS_FLAGS
