#:schema https://raw.githubusercontent.com/rogue-sly/dotbee/refs/heads/main/schema/dotbee.json

[settings]
on_conflict = "ask"  # overwrite, adopt, skip, abort or ask (default: ask)

# global configs that gets applied regardless of profile
[global.links]
"~/.bashrc" = "bash/bashrc"
"~/.gitconfig" = "git/gitconfig"

# each profile below is a collection of configs

# desktop profile
[profiles.desktop.links]
"~/.config/i3/config" = "linux/i3_config"
"~/.config/polybar/config" = "linux/polybar_config"

# server profile
[profiles.server.links]
"~/.tmux.conf" = "server/tmux.conf"

# termux profile
[profiles.termux.links]
"~/.termux" = "termux/.termux"
