#:schema https://raw.githubusercontent.com/rogue-sly/dotbee/refs/heads/main/schema/dotbee.json

[settings]
on_conflict = "ask"  # overwrite, adopt, skip, abort or ask (default: ask)

# global configs that gets applied regardless of profile
[global.links]
bashrc = { src = "bash/bashrc", dst = "~/.bashrc" }
gitconfig = { src = "git/gitconfig", dst = "~/.gitconfig" }

# each profile below is a collection of configs

# desktop profile
[profiles.desktop.links]
i3_config = { src = "linux/i3_config", dst = "~/.config/i3/config" }
polybar_config = { src = "linux/polybar_config", dst = "~/.config/polybar/config" }

# server profile
[profiles.server.links]
tmux_conf = { src = "server/tmux.conf", dst = "~/.tmux.conf" }

# termux profile
[profiles.termux.links]
termux = { src = "termux/.termux", dst = "~/.termux" }
