#:schema https://gitlab.com/rogue87/dotsy/-/raw/main/schema/dotsy.json

[settings]
auto_detect_profile = true # try to match hostname to a profile
on_conflict = "ask"        #  overwrite, adopt, skip, abort or ask (default: ask)
icon_style = "text"

# global configs that gets applied regardless of profile
[global.links]
"~/.bashrc" = "bash/bashrc"
"~/.gitconfig" = "git/gitconfig"

# each profile below is a collection of configs

# desktop profile
[profiles.desktop.links]
"~/.config/i3/config" = "linux/i3_config"
"~/.config/polybar/config" = "linux/polybar_config"

# server profile
[profiles.server.links]
"~/.tmux.conf" = "server/tmux.conf"

# termux profile
[profiles.termux.links]
"~/.termux" = "termux/.termux"
