#!/bin/env bash
#USAGE flag "-p --profile <profile>" help="Build with the specified profile" default="dev" {
#USAGE   choices "dev" "release"
#USAGE }
#USAGE flag "-t --target <target>" help="The target to build" default="x86_64-unknown-linux-gnu" {
#USAGE   choices "aarch64-linux-android" "aarch64-unknown-linux-musl" "x86_64-unknown-linux-gnu"
#USAGE }

set -e

# Set build mode variable
BUILD_MODE="debug"
if [[ "${usage_profile?}" == "release" ]]; then
    BUILD_MODE="release"
fi

echo
echo "TARGET : ${usage_target?}"
echo "PROFILE: ${usage_profile?}"
echo

cargo build --profile "${usage_profile?}" --target "${usage_target?}"

echo "Building testing container image..."
podman build -t dotbee-dev "$(dirname "$0")"

# Detect if we are using podman
PODMAN_FLAGS=""
if podman --version | grep -qi podman; then
    PODMAN_FLAGS="--userns=keep-id"
fi

BIN_PATH="$(pwd)/target/${usage_target}/${BUILD_MODE}/dotbee"

echo "Running testing container..."
podman run --hostname="laptop" -it --rm \
    $PODMAN_FLAGS \
    -v "${BIN_PATH}:/usr/local/bin/dotbee:Z" \
    dotbee-dev
